server:
  port: 8083
  servlet:
    context-path: /seguranca

spring:
  application:
    name: seguranca
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      enabled: true
  jmx:
    enabled: false
  datasource:
      url: jdbc:mysql://localhost:3306/seguranca
      username: root
      password: 
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka

security:
  jwt: 
    token:
      secret-key: chave_microservico
      expire-length: 360000
      
      