server:
  port: 8080

spring:
  application:
    name: gateway
    
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka

zuul:  prefix: /api
  ignored-services: "*"
  
  routes:    cliente:
      path: /cliente/**
      service-id: cliente
      strip-prefix: false
      custom-sensitive-headers: true
    fornecedor:
      path: /fornecedor/**
      service-id: fornecedor
      strip-prefix: false
      custom-sensitive-headers: true
      
      
                  