server:
  port: 8082
  servlet:
    context-path: /fornecedor

spring:
  application:
    name: fornecedor
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jmx:
    enabled: false
  datasource:
      url: jdbc:mysql://localhost:3306/fornecedor
      username: root
      password: 
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka
        