server:
  port: 8081
  servlet:
    context-path: /cliente

spring:
  application:
    name: cliente
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      enabled: true
  jmx:    enabled: false
     
  datasource:
      url: jdbc:mysql://localhost:3306/cliente
      username: root
      password: 
 
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka
      
        